INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC201', 'Computer Science I for Majors', '4');;
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC202', 'Computer Science IU for Majors', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC304', 'Social and Ethical Issues in Information Technology', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC486', 'Mobile Telephony Communications', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC484', 'Java Server Technologies', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC457', 'Quantum Computation', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC452', 'Logic for Computer Science', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC451', 'Automata Theory and Formal Languages', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC203', 'Discrete Structures', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC313', 'Computer Organization and Assembly Language Programming', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC411', 'Computer Architecture', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC435', 'Computer Graphics', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC331', 'Principles of Programming Language', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC431', 'Compiler Design Principles', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC432', 'Object-Oriented Programming Languages and Systems', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC433', 'Scripting Languages', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC473', 'Introduction to Natural Language Processing', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC471', 'Introduction to Artificial Intelligence', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC493', 'Capstone Games Group Project', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC479', 'Introduction to Robotics', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC478', 'Introduction to Machine Learning', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC477', 'Agent Architectures and Multi-Agent Systems', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC447', 'Software Engineering I', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC448', 'Software Engineering II', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC427', 'Wearable Computing', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC436', 'Data Visualization', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC437', 'Graphical User Interface Programming', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC441', 'Design and Analysis of Algorithms.', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC443', 'Cryptology', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC453', 'Applied Combinatorics and Graph Theory', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC455', 'Numerical Computations', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC456', 'Symbolic Computation', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC476', 'Information Retrieval', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC475', 'Introduction to Neural Networks', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC421', 'Principles of Operating Systems', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC426', 'Principles of Computer Security', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC483', 'Parallel and Distributed Processing', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC487', 'Introduction To Network Security', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC465', 'Introduction to Electronic Commerce', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC466', 'Electronic Commerce Technology', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC481', 'Computer Networks', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC461', 'Database Management Systems', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC341', 'Data Structures', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC291', 'Special Topics in Computer Science', '1 - 4''');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC299', 'Independent Study in Computer Science', '1 - 4''');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CMSC499', 'Independent Study in Computer Science', '1 - 4''');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('STAT355', 'Introduction to Probability and Statistics for Scientists and Engineers', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CHEM101', 'Principles of Chemistry I', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CHEM102', 'Principles of Chemistry II', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('CHEM102L', 'Introductory Chemistry Lab I', '2');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('GES110', 'Physical Geography', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('BIOL141', 'Foundations of Biology: Cells, Energy and Organisms', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('BIOL142', 'Foundations of Biology: Ecology and Evolution', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('SCI100', 'Water; An Interdisciplinary Study (MS)', '3');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('SCI101L', 'Quantitative Reasoning: Measurement and Skills Lab', '2');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('PHYS121', 'Introductory Physics I', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('PHYS122', 'Introductory Physics II', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('GES286', 'Ecploring the Environment: A Geo-Spatial Perspective', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('PHYS122L', 'Introductory Physics Laboratory', '2');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('MATH251', 'Multivariable Calculus', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('MATH151', 'Calculus and Analytic Geometry I', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('MATH152', 'Calculus and Analytic Geometry II', '4');
INSERT INTO `Courses`(`course_ID`, `course_name`, `course_credits`) VALUES ('MATH221', 'Introduction to Linear Algebra', '3');